name: generate
on:
  - push

env:
  DOCKER_TTY: ""  # using `docker run -t` seems to not work in github actions, maybe related to https://github.com/actions/runner/issues/241
  
jobs:
  generate:
    name: Generate assets and check for diff
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
      # Run autogeneration and see if there are differences
      - run: make autogen && make tidy-in-docker && make api-docs && git status --short
      # Check so that there weren't any modified files
      - run: echo "This fails if there are modified files, otherwise succeeds." && git status --short && git --no-pager diff && [[ -z $(git status --short) ]] && echo "Success, no diff!"
