name: go-test
on:
  - push

jobs:
  gotest:
    name: go test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
      - uses: crazy-max/ghaction-setup-containerd@v2
      - run: make test
