name: Release kernel images

on:
  workflow_dispatch:
    inputs:
      user:
        description: Container registry user.
        default: sourcegraph
        required: true

env:
  DOCKER_USER: ${{ github.event.inputs.user }}

defaults:
  run:
    working-directory: images/kernel

jobs:
  kernel:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        version: [ 5.10.135, 6.1.140 ]
    env:
      KERNEL_VERSIONS: ${{ matrix.version }}
    steps:
      - uses: actions/checkout@v2
      # - name: Login to container registry
      # uses: docker/login-action@v1.14.1
      # with:
      #   registry: docker.io
      #   username: ${{ secrets.DOCKER_USERNAME }}
      #   password: ${{ secrets.DOCKER_PASSWORD }}
      - run: make
        env:
          GOARCH: amd64
      - run: make
        env:
          GOARCH: arm64
      # - run: make push
