name: Upload release assets

on:
  workflow_dispatch:
    # Enable manual trigger of this action.
    inputs:
      user:
        description: Container registry user.
        default: sourcegraph
        required: true

      tag:
        description: Git tag to checkout.
        required: true

env:
  DOCKER_TTY: ""  # using `docker run -t` seems to not work in github actions, maybe related to https://github.com/actions/runner/issues/241
  REL_TAG: ${{ github.event.inputs.tag }}
  DOCKER_USER: ${{ github.event.inputs.user }}

jobs:
  build-and-upload:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ env.REL_TAG }}
      - name: Build binaries
        run: make build-all
      - name: Login to container registry
        uses: docker/login-action@v1.14.1
        with:
          registry: docker.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Push sandbox image
        run: make release-only
      - name: Prepare assets
        run: |
          mkdir -p release
          cp bin/releases/${{ env.REL_TAG }}/amd64/ignite release/ignite-amd64
          cp bin/releases/${{ env.REL_TAG }}/amd64/ignited release/ignited-amd64
          cp bin/releases/${{ env.REL_TAG }}/arm64/ignite release/ignite-arm64
          cp bin/releases/${{ env.REL_TAG }}/arm64/ignited release/ignited-arm64
      - name: Upload assets
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ env.REL_TAG }}
          file_glob: true
          file: release/*
          overwrite: true
